# базовый образ
FROM python:3.12

# Убираем мусор 
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Рабочая дериктория
WORKDIR /app

# Система зависимостей
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install  --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Копируем проет 
COPY . .